"""Add json_data field to sessions

Revision ID: 117cdc597705
Revises: 578cd6cf963d
Create Date: 2025-01-08 12:03:16.936942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117cdc597705'
down_revision: Union[str, None] = '578cd6cf963d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def upgrade():
    op.add_column('sessions', sa.Column('json_data', sa.JSON(), nullable=True))

def downgrade():
    op.drop_column('sessions', 'json_data')

