"""Add description column to subject

Revision ID: f75b8d73462c
Revises: 
Create Date: 2024-12-29 20:15:23.927118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f75b8d73462c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.alter_column('gruppa', 'faculty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_gruppa_id_gruppa'), 'gruppa', ['id_gruppa'], unique=False)
    op.alter_column('sessions', 'type_of_control',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('sessions', 'teacher',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=False)
    op.alter_column('subject', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_subject_id_subject'), 'subject', ['id_subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subject_id_subject'), table_name='subject')
    op.alter_column('subject', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.alter_column('sessions', 'teacher',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'type_of_control',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_gruppa_id_gruppa'), table_name='gruppa')
    op.alter_column('gruppa', 'faculty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.create_table('session',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('type_of_control', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('teacher', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gruppa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gruppa_id'], ['gruppa.id_gruppa'], name='session_gruppa_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id_subject'], name='session_subject_id_fkey'),
    sa.PrimaryKeyConstraint('session_id', name='session_pkey')
    )
    # ### end Alembic commands ###
